# Dockerfile which loads and indexes new data into empty data container image

FROM hsldevcom/pelias-data-container-base
MAINTAINER Reittiopas version: 0.1

RUN /bin/bash -c "source /mnt/tools/scripts/getdata.sh"

#entrypoint (elasticsearch) comes from base image
