# Dockerfile which loads and indexes new data into empty data container image
MAINTAINER Reittiopas version: 0.1

ARG ORG="hsldevcom"

FROM ${ORG}/pelias-data-container-base

RUN /bin/bash -c "source /mnt/tools/scripts/getdata.sh"

#entrypoint (elasticsearch) comes from base image
