# Dockerfile for image which runs the data loader and builds and deploys the final image

FROM docker:20.10.7-dind

# fuzzy testing threshold
ARG THRESHOLD

WORKDIR /mnt

ADD Dockerfile.loader ${WORKDIR}
ADD scripts/build-data-container.sh ${WORKDIR}
ADD pelias.json ${WORKDIR}

RUN apk add --no-cache alpine-sdk bash bc curl git jq python3 sed grep coreutils nodejs nodejs-npm

RUN git clone --single-branch https://github.com/hsldevcom/pelias-fuzzy-tests \
  && cd pelias-fuzzy-tests \
  && npm install

CMD ( dockerd-entrypoint.sh --log-level=error > /dev/null 2>&1 & ) && \
    unset DOCKER_HOST && \
    until docker info > /dev/null 2>&1; do \
    echo "Waiting for Docker to start."; \
    sleep 1; \
    done && \
    echo "Docker is running!" && \
    /bin/bash /mnt/build-data-container.sh
